spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=psql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# MAXIMO DE CONEXIONES ABIERTS 
server.tomcat.max-connections=1000

server.port=8080
server.ssl.enabled=false

server.error.include-message=always
server.error.include-binding-errors=always

#cola de espera
server.tomcat.accept-count=100
#maximo de peticiones simultaneias
server.tomcat.threads.max=200

