spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=psql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.tomcat.max-connections=1000

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=18241824
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

