spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:psql}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
# MAXIMO DE CONEXIONES ABIERTS 
server.tomcat.max-connections=1000

server.port=8080
server.ssl.enabled=false

server.error.include-message=always
server.error.include-binding-errors=always

#cola de espera
server.tomcat.accept-count=100
#maximo de peticiones simultaneias
server.tomcat.threads.max=200

